name: Makefile CI


on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04-arm

    steps:
    - uses: actions/checkout@v4
      with: 
        repository: MarcSabatella/soundfont-cmdline-tools
    - run: make
    - uses: actions/upload-artifact@v4
      with:
        name: sf2-tools
        path: |
         ./sf2-split
         ./sf2-test
