name: Makefile CI


on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04-arm

    steps:
    - uses: actions/checkout@v4
      with: 
        repository: MarcSabatella/soundfont-cmdline-tools
    - run: make
