name: Makefile CI


on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04-arm

    steps:
    - uses: actions/checkout@v4
      with: 
        repository: enikey87/sf2-utils
    - uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - run: make all
    - name: Print Folder Tree
      uses: jaywcjlove/github-action-folder-tree@main
      with:
        path: ./
    - uses: actions/upload-artifact@v4
      with:
        name: sf2-tools
        path: |
         ./sf2-split
         ./sf2-test
         ./sf2-keyrange
         ./sf2-split-json.py
         ./sf2-split.sh
