name: mossy


on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-24.04-arm
    
    steps:
    - uses: actions/checkout@v5
      with: 
        repository: git-moss/ConvertWithMoss
    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '25'
    - run: make
    - name: Print Folder Tree
      uses: jaywcjlove/github-action-folder-tree@main
      with:
        path: ./
