name: mossy


on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-24.04-arm
    
    steps:
    - uses: actions/checkout@v5
      with: 
        repository: git-moss/ConvertWithMoss
    - uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '25'
    - run: mvn -B package jpackage::jpackage@linux --file pom.xml
    - name: Print Folder Tree
      uses: jaywcjlove/github-action-folder-tree@main
      with:
        path: ./
    - uses: actions/upload-artifact@v4
      with:
        name: cwithmarm
        path: ./target/releases/convertwithmoss_14.2.0_arm64.deb
